##########################
# Services Configuration #
##########################
log_level: "debug"

mainnet:
  api: "https://api.gmp.axelarscan.io"
  forecall:
    concurrent_transaction: 20
    delay_ms_per_batch: 5000
    gas_remain_x_threshold: 2.0
  chains:
    ethereum:
      contract_address: ""
      endpoints:
        rpc:
          - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/eth"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    binance:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/bsc"
          - "https://bscrpc.com"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    polygon:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/polygon"
          - "https://matic-mainnet.chainstacklabs.com"
          - "https://polygon-rpc.com"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    avalanche:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/avalanche"
          - "https://api.avax.network/ext/bc/C/rpc"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    fantom:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/fantom"
          - "https://rpc.ftm.tools"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    moonbeam:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/moonbeam"
          - "https://rpc.api.moonbeam.network"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    aurora:
      contract_address: ""
      endpoints:
        rpc:
          - "https://mainnet.aurora.dev"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.2
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50



testnet:
  api: "https://testnet.api.gmp.axelarscan.io"
  forecall:
    concurrent_transaction: 20
    delay_ms_per_batch: 5000
    gas_remain_x_threshold: 2.0
  chains:
    ethereum:
      contract_address: ""
      endpoints:
        rpc:
          - "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/eth_goerli"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    binance:
      contract_address: ""
      endpoints:
        rpc:
          - "https://data-seed-prebsc-1-s1.binance.org:8545"
          - "https://data-seed-prebsc-2-s1.binance.org:8545"
          - "https://data-seed-prebsc-1-s2.binance.org:8545"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    polygon:
      contract_address: ""
      endpoints:
        rpc:
          - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/polygon_mumbai"
          - "https://matic-mumbai.chainstacklabs.com"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    avalanche:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/avalanche_fuji"
          - "https://api.avax-test.network/ext/bc/C/rpc"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    fantom:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.ankr.com/fantom_testnet"
          - "https://rpc.testnet.fantom.network"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    moonbeam:
      contract_address: ""
      endpoints:
        rpc:
          - "https://rpc.api.moonbase.moonbeam.network"
          - "https://rpc.testnet.moonbeam.network"
          - "https://moonbase-alpha.public.blastapi.io"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fastest"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50
    aurora:
      contract_address: ""
      endpoints:
        rpc:
          - "https://testnet.aurora.dev"
      ozd:
        api_key: ""
        api_secret: ""
        speed: "fast"
      wallet:
        private_key: ""
      default_gas_limit: "700000"
      gas_adjustment_rate: 1.4
      symbols:
        USDC:
          decimals: 6
          min: 5
          max: 50