version: '3.6'
services:
  axelar-gmp-express:
    container_name: axelar-gmp-express
    image: node:17.7.2-alpine
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_NO_WARNINGS=1
      - ENVIRONMENT=testnet
    volumes:
      - .:/usr/src/axelar-gmp-express
      - node_modules:/usr/src/axelar-gmp-express/node_modules
    networks:
      - axelar-gmp-express
    command: npm run start
volumes:
  node_modules:
networks:
  axelar-gmp-express:
    driver: bridge